### ISSUE TITLE
Estrutura da página de login

### ISSUE THREAD

**Issue by danielfsousa** [jsrmjr/time2#1]
Temos que tirar a navegação da esquerda da página de login. Como todas as rotas herdam do template padrão, a tela de login fica desse jeito:

![entrar](https://cloud.githubusercontent.com/assets/11372312/19730118/f297f8fe-9b77-11e6-9371-5e5f850e3e53.PNG)

Possíveis soluções:
Mudar o route do angular para o UI-Router ou usar ng-include na página de login

**Comment by daniloleemes** [comment]
Eu criei um novo branch usando as rotas q o Ionic usa, tá dando certo, agora só preciso ajustar o layout que tá cortando. O menu aparece, com a rota certinha, porém o conteúdo não aparece redimensionando. 
![captura de tela 2016-10-26 as 13 16 19](https://cloud.githubusercontent.com/assets/13068064/19732094/660bc3d2-9b7e-11e6-9168-aa4796876f76.png)

**Comment by danielfsousa** [comment]
Verifica se você não esqueceu da div `content-wrapper` ou se ele está criando uma div a mais.

Vou te dar um exemplo da rota que estamos usando agora...


Dá bug porque o `ng-view` é uma div a mais no `content-wrapper`:
```
<div class="content-wrapper">
    <ng-view></ng-view>
</div>
```

Não dá bug porque o `ng-view` não cria nenhuma div a mais dentro do `content-wrapper`
`<div ng-view class="content-wrapper"></div>`

**Comment by daniloleemes** [comment]
To tentando aqui mas sem sucesso...

**Comment by daniloleemes** [comment]
No caso o novo branch, teve que ficar com o esquema assim:

index:
```
<body ...>
<ion-nav-view></ion-nav-view>
</body>
```

menu:
```
<div class="wrapper">
<todo o layout base>
<ion-nav-view> conteudo </ion-nav-view>
</div>
```

**Comment by daniloleemes** [comment]
Arrumei, vou dar um merge no master

**Comment by daniloleemes** [comment]
```html
<div class="content-wrapper">
    <ion-nav-view name="menuContent"></ion-nav-view>
</div>
```
